# Maximum number of channels to return per request
max_channels = 512

channels_find_limit = 200
wait_time = 500

events_find_limit = 100
msgs_find_limit = 10
analytics_find_limit_v5 = 5000
analytics_maxtime_v5 = 20000

heartbeat_time = 30000
health_threshold_promilles = 950
health_unsignable_promilles = 750
propagation_timeout = 1000

fetch_timeout = 5000
validator_tick_timeout = 5000

ip_rate_limit = { type = 'ip', timeframe = 20000 }
sid_rate_limit = { type = 'sid', timeframe = 20000 }

# TODO: Replace with real contract address
outpace_address = '0x333420fc6a897356e69b62417cd17ff012177d2b'
# TODO: Replace with real contract address
sweeper_address = '0x333420fc6a897356e69b62417cd17ff012177d2b'

ethereum_network = 'http://localhost:8545'
ethereum_adapter_relayer = 'https://goerli-relayer.adex.network'

creators_whitelist = []
validators_whitelist = []

[[token_address_whitelist]]
# DAI
address = '0x73967c6a0904aa032c103b4104747e88c566b1a2'
# 1 * 10^-10 = 0.0_000_000_001
min_token_units_for_deposit = '100000000'
min_validator_fee = '100000000'
precision = 18

[[token_address_whitelist]]
# USDT
address = '0x509ee0d083ddf8ac028f2a56731412edd63223b9'
# 1.000_000
min_token_units_for_deposit = '1000000'
# 0.001
min_validator_fee = '1000'
precision = 6

[[token_address_whitelist]]
# USDC
address = '0x44dcfcead37be45206af6079648988b29284b2c6'
# 1.000_000
min_token_units_for_deposit = '100000000'
# 0.001
min_validator_fee = '1000'
precision = 6
