[package]
name = "store"
version = "0.1.0"
authors = ["Samparsky"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.3", features = ["postgres"] }